apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: specfem
  name: specfem
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: {{ .App.Spec.Resources.StorageClassName }}
  volumeMode: Filesystem
