apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: specfem
  name: save-solver-output
spec:
  backoffLimit: 1
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        app: specfem
      name: save-solver-output
    spec:
      containers:
      - name: cnt
        command:
        - bash
        - -c
        - "ls $SHARED_VOLUME"
        env:
        - name: SHARED_VOLUME
          value: /mnt/shared/
        volumeMounts:
        - mountPath: /mnt/shared/
          name: shared-volume
        image: registry.access.redhat.com/ubi8/ubi
        volumeMounts:
        - mountPath: /mnt/shared/
          name: shared-volume
      restartPolicy: Never
      volumes:
      - name: shared-volume
        persistentVolumeClaim:
          claimName: specfem
