apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  #finalizers:
  #- kubernetes.io/pvc-protection
  labels:
    app: specfem
  name: specfem
spec:
  accessModes:
  {{ if eq .App.Spec.Exec.Nproc 1 }}
  - ReadWriteOnce
  {{ else }}
  - ReadWriteOnce
  {{ end }}
  resources:
    requests:
      storage: 100Gi
  storageClassName: {{ .App.Spec.Resources.StorageClassName }}
  volumeMode: Filesystem
