apiVersion: v1
kind: Pod
metadata:
  labels:
    app: specfem
  name: mesher2solver-builder
spec:
  containers:
  - command:
    - /bin/sh
    - /mnt/helper/run_mesher2solver.sh
    image: image-registry.openshift-image-registry.svc:5000/{{ .App.ObjectMeta.Namespace }}/specfem:mesher2solver_helper
    name: mesher2solver-builder
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /mnt/shared/
      name: shared-volume
    - mountPath: /mnt/helper/run_mesher2solver.sh
      name: run-mesher2solver-sh
      readOnly: true
      subPath: run_mesher2solver.sh
    - mountPath: /var/run/secrets/openshift.io/push
      name: builder-dockercfg-push
      readOnly: true
  nodeSelector:
    buildah.specfem.build: ""
  restartPolicy: Never
  volumes:
  - name: shared-volume
    persistentVolumeClaim:
      claimName: specfem
  - configMap:
      defaultMode: 511
      name: run-mesher2solver-sh
    name: run-mesher2solver-sh
  - name: builder-dockercfg-push
    secret:
      defaultMode: 384
      secretName: {{ .Cfg.SecretNames.DockerCfgPush}}
