apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: specfem
  name: save-solver-output
spec:
  backoffLimit: 6
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        app: specfem
      name: save-solver-output
    spec:
      containers:
      - command:
        - bash 
        - -c 
        - "CACHE_NAME=cache/${SPECFEM_MPI_NPROC}proc/${SPECFEM_NEX}nex; cat /mnt/shared/${CACHE_NAME}/OUTPUT_FILES/output_solver.txt"
        env:
        - name: SPECFEM_NEX
          value: "{{ .App.Spec.Specfem.Nex }}"
        - name: SPECFEM_MPI_NPROC
          value: "{{ .App.Spec.Exec.Nproc }}"
        image: docker.io/centos:7
        name: save-solver-output
        volumeMounts:
        - mountPath: /mnt/shared/
          name: shared-volume
      restartPolicy: Never
      volumes:
      - name: shared-volume
        persistentVolumeClaim:
          claimName: specfem
