apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: specfem
  name: {{ .Cfg.Job.Name }}
spec:
  activeDeadlineSeconds: 150
  backoffLimit: 0
  completions: 1
  parallelism: 1
  template:
    metadata:
      name: {{ .Cfg.Job.Name }}
      labels:
        app: specfem
    spec:
      containers:
      - name: run
        image: image-registry.openshift-image-registry.svc:5000/{{ .App.ObjectMeta.Namespace }}/specfem:project
        imagePullPolicy: Always
        command:
        - bash
        - /mnt/helper/{{ .Cfg.Job.Entrypoint }}
        env:
        - name: DATA_DIR
          value: /mnt/shared
        volumeMounts:
        - mountPath: /mnt/shared/
          name: shared-volume
        - mountPath: /mnt/helper/{{ .Cfg.Job.Entrypoint }}
          name: {{ .Cfg.Job.ConfigMap }}
          readOnly: true
          subPath: {{ .Cfg.Job.Entrypoint }}
        buildah.specfem.build:
      restartPolicy: Never
      volumes:
      - name: shared-volume
        persistentVolumeClaim:
          claimName: specfem
      - configMap:
          defaultMode: 511
          name: {{ .Cfg.Job.ConfigMap }}
        name: {{ .Cfg.Job.ConfigMap }}
