FROM specfem:base

#RUN git clone "$SPECFEM_GIT_REPO" -b "$SPECFEM_GIT_BRANCH" --depth 1 /app

RUN mkdir /app && echo "$(date) | Cloned '$SPECFEM_GIT_REPO' branch '$SPECFEM_GIT_BRANCH'" >> /app/SPECFEM
