apiVersion: specfem.kpouget.psap/v1alpha1
kind: SpecfemApp
metadata:
  name: specfem-sample
  namespace: specfem
spec:
  exec:
    ncore: 32
    nproc: 4
    slotsPerWorker: 4
  git:
    ref: master
    uri: https://gitlab.com/kpouget_psap/specfem3d_globe.git
  resources:
    networkType: Default
    relyOnSharedFS: 'false'
    storageClassName: local-store
    useUbiImage: true
    workerNodeSelector:
      kubernetes.io/hostname: perf23-nva100
      node-role.kubernetes.io/worker: null
    requests:
      nvidia.com/gpu: 4
  specfem:
    nex: 64
    gpuPlatform: NVIDIA
    gpuDevice: '*'
