apiVersion: specfem.kpouget.psap/v1alpha1
kind: SpecfemApp
metadata:
  name: specfem-sample
  namespace: specfem
spec:
  git:
    uri: https://gitlab.com/kpouget_psap/specfem3d_globe.git
    ref: master
  exec:
    nproc: 16
    ncore: 4
    slotsPerWorker: 2
  specfem:
    nex: 128
  resources:
    useUbiImage: true
    storageClassName: "ocs-external-storagecluster-cephfs"
    workerNodeSelector:
      node-role.kubernetes.io/worker:
    relyOnSharedFS: false
