apiVersion: specfem.kpouget.psap/v1alpha1
kind: SpecfemApp
metadata:
  name: specfem-sample
  namespace: specfem
spec:
  exec:
    ncore: 16
    nproc: 4
    slotsPerWorker: 2
  git:
    ref: master
    uri: https://gitlab.com/kpouget_psap/specfem3d_globe.git
  resources:
    multus:
      mainNic: enp1s0f1
    networkType: Default
    relyOnSharedFS: 'True'
    storageClassName: ocs-external-storagecluster-cephfs
    useUbiImage: true
    workerNodeSelector:
      node-role.kubernetes.io/worker: null
  specfem:
    nex: 64
