apiVersion: specfem.kpouget.psap/v1alpha1
kind: SpecfemApp
metadata:
  name: specfem-sample
  namespace: test-specfem
spec:
  namespace: test-specfem
  exec:
    ncore: 16
    nproc: 4
    slotsPerWorker: 2
  git:
    uri: https://github.com/geodynamics/specfem3d.git
    ref: master
  resources:
    multus:
      mainNic: enp1s0f1
    networkType: Default
    relyOnSharedFS: true
    storageClassName:
    useUbiImage: true
    workerNodeSelector:
      node-role.kubernetes.io/worker: null
  specfem:
    nex: 16
